# Generated by Django 5.2.10 on 2026-02-17 20:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BAARecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("organization_name", models.CharField(max_length=255)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
                ("contact_email", models.EmailField(max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Signature"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("terminated", "Terminated"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "BAA Record",
                "verbose_name_plural": "BAA Records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataRetentionPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("recordings", "Meeting Recordings"),
                            ("transcripts", "Meeting Transcripts"),
                            ("connection_logs", "Connection Logs"),
                            ("audit_logs", "Audit Logs"),
                            ("chat_messages", "Chat Messages"),
                            ("session_data", "Session Data"),
                            ("export_files", "Data Export Files"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "retention_days",
                    models.IntegerField(
                        help_text="Number of days to retain data. 0 = indefinite."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                ("last_cleanup_at", models.DateTimeField(blank=True, null=True)),
                ("records_deleted_last_run", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Data retention policies",
            },
        ),
        migrations.CreateModel(
            name="DataDeletionRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_email", models.EmailField(max_length=254)),
                ("username", models.CharField(max_length=150)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("denied", "Denied"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("data_categories_deleted", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="DataExportRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("ready", "Ready for Download"),
                            ("downloaded", "Downloaded"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("file_path", models.CharField(blank=True, max_length=500)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="PHIAccessLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("user_email", models.CharField(max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("view", "Viewed"),
                            ("create", "Created"),
                            ("update", "Updated"),
                            ("delete", "Deleted"),
                            ("export", "Exported"),
                            ("share", "Shared"),
                        ],
                        max_length=10,
                    ),
                ),
                ("resource_type", models.CharField(max_length=100)),
                ("resource_id", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("organization_id", models.UUIDField(blank=True, null=True)),
                (
                    "justification",
                    models.TextField(blank=True, help_text="Reason for accessing PHI"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "PHI Access Log",
                "verbose_name_plural": "PHI Access Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("user_email", models.CharField(blank=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("auth", "Authentication"),
                            ("user", "User Management"),
                            ("org", "Organization Management"),
                            ("meeting", "Meeting Operations"),
                            ("recording", "Recording Operations"),
                            ("billing", "Billing Operations"),
                            ("admin", "Admin Operations"),
                            ("data", "Data Access/Export"),
                            ("compliance", "Compliance Actions"),
                            ("security", "Security Events"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=100)),
                ("description", models.TextField()),
                ("resource_type", models.CharField(blank=True, max_length=100)),
                ("resource_id", models.CharField(blank=True, max_length=255)),
                (
                    "organization_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("success", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["category", "timestamp"],
                        name="compliance__categor_4fe699_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="compliance__user_id_761f53_idx",
                    ),
                    models.Index(
                        fields=["action", "timestamp"],
                        name="compliance__action_884b0d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.CharField(blank=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("cookies_essential", "Essential Cookies"),
                            ("cookies_analytics", "Analytics Cookies"),
                            ("cookies_marketing", "Marketing Cookies"),
                            ("data_processing", "Data Processing"),
                            ("communications", "Marketing Communications"),
                            ("recording", "Meeting Recording Consent"),
                            ("transcript", "Transcript Processing"),
                        ],
                        max_length=30,
                    ),
                ),
                ("granted", models.BooleanField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "consent_type"],
                        name="compliance__user_id_130759_idx",
                    ),
                    models.Index(
                        fields=["session_id", "consent_type"],
                        name="compliance__session_be266a_idx",
                    ),
                ],
            },
        ),
    ]
