# Generated by Django 5.2.10 on 2026-02-04 21:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0005_organization_recording_to_s3"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("pro", "Pro"),
                            ("business", "Business"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("monthly_price_cents", models.IntegerField(default=0)),
                ("annual_price_cents", models.IntegerField(default=0)),
                ("is_per_user", models.BooleanField(default=False)),
                (
                    "stripe_product_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "stripe_monthly_price_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "stripe_annual_price_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("max_rooms", models.IntegerField(default=1)),
                ("max_participants", models.IntegerField(default=4)),
                ("max_meeting_duration_minutes", models.IntegerField(default=30)),
                ("recording_enabled", models.BooleanField(default=False)),
                ("custom_branding", models.BooleanField(default=False)),
                ("custom_subdomain", models.BooleanField(default=False)),
                ("breakout_rooms", models.BooleanField(default=False)),
                ("waiting_rooms", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("past_due", "Past Due"),
                            ("canceled", "Canceled"),
                            ("incomplete", "Incomplete"),
                            ("incomplete_expired", "Incomplete Expired"),
                            ("trialing", "Trialing"),
                            ("unpaid", "Unpaid"),
                            ("paused", "Paused"),
                        ],
                        default="active",
                        max_length=30,
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("annual", "Annual")],
                        default="monthly",
                        max_length=10,
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("current_period_start", models.DateTimeField(blank=True, null=True)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                ("canceled_at", models.DateTimeField(blank=True, null=True)),
                ("quantity", models.IntegerField(default=1)),
                (
                    "is_complimentary",
                    models.BooleanField(
                        default=False,
                        help_text="Granted by super admin, bypasses Stripe",
                    ),
                ),
                ("complimentary_note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="users.organization",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="billing.plan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stripe_invoice_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "stripe_charge_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("amount_cents", models.IntegerField()),
                ("currency", models.CharField(default="usd", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("pending", "Pending"),
                            ("refunded", "Refunded"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("invoice_pdf_url", models.URLField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="billing.subscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UsageRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("meeting_minutes", "Meeting Minutes"),
                            ("participants", "Participants"),
                            ("recordings", "Recordings"),
                            ("storage_bytes", "Storage (bytes)"),
                        ],
                        max_length=30,
                    ),
                ),
                ("value", models.BigIntegerField(default=0)),
                ("recorded_at", models.DateField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="users.organization",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["stripe_customer_id"], name="billing_sub_stripe__97887e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["stripe_subscription_id"], name="billing_sub_stripe__abc269_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["status"], name="billing_sub_status_948046_idx"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["current_period_end"], name="billing_sub_current_c59a21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["stripe_invoice_id"], name="billing_pay_stripe__5ad6f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["subscription", "-created_at"],
                name="billing_pay_subscri_d33e55_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usagerecord",
            index=models.Index(
                fields=["organization", "metric", "recorded_at"],
                name="billing_usa_organiz_727a7f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usagerecord",
            index=models.Index(
                fields=["recorded_at"], name="billing_usa_recorde_aeaf0a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usagerecord",
            unique_together={("organization", "metric", "recorded_at")},
        ),
    ]
