# Generated by Django 5.2.10 on 2026-02-07 18:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_stripe_to_payu_fields"),
        ("users", "0007_add_billing_info_and_invoice"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "billing_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "address_line1",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "address_line2",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("state", models.CharField(blank=True, default="", max_length=100)),
                (
                    "postal_code",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ISO 3166-1 alpha-2 country code",
                        max_length=2,
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="GST/VAT/Tax ID number",
                        max_length=50,
                    ),
                ),
                (
                    "tax_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Tax type: GST, VAT, EIN, ABN, etc.",
                        max_length=10,
                    ),
                ),
                (
                    "billing_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_info",
                        to="users.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Billing Info",
                "verbose_name_plural": "Billing Info",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                (
                    "billing_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("billing_address", models.TextField(blank=True, default="")),
                (
                    "billing_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("tax_id", models.CharField(blank=True, default="", max_length=50)),
                ("tax_type", models.CharField(blank=True, default="", max_length=10)),
                ("line_items", models.JSONField(blank=True, default=list)),
                ("subtotal_cents", models.IntegerField(default=0)),
                ("tax_amount_cents", models.IntegerField(default=0)),
                ("total_cents", models.IntegerField(default=0)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("issued", "Issued"),
                            ("paid", "Paid"),
                            ("void", "Void"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("issued_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("paid_date", models.DateField(blank=True, null=True)),
                (
                    "pdf_url",
                    models.URLField(
                        blank=True, default="", help_text="S3 URL to generated PDF"
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="users.organization",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice",
                        to="billing.payment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "-created_at"],
                        name="billing_inv_organiz_7d8ebd_idx",
                    ),
                    models.Index(
                        fields=["invoice_number"], name="billing_inv_invoice_70511c_idx"
                    ),
                    models.Index(
                        fields=["status"], name="billing_inv_status_541249_idx"
                    ),
                    models.Index(
                        fields=["issued_date"], name="billing_inv_issued__719d01_idx"
                    ),
                ],
            },
        ),
    ]
