# Generated by Django 4.2.7 on 2026-01-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0003_personalroom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="room_id",
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="personalroom",
            name="room_id",
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="usermeetingpacket",
            name="room_id",
            field=models.CharField(max_length=20),
        ),
    ]
