# Generated by Django 4.2.7 on 2026-01-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0004_alter_meeting_room_id_alter_personalroom_room_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="attendees_emails",
            field=models.TextField(
                blank=True, default="", help_text="Comma-separated email addresses"
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="meeting",
            name="is_all_day",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="meeting",
            name="location",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="meeting",
            name="recurrence",
            field=models.CharField(
                choices=[
                    ("none", "Does not repeat"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("biweekly", "Every 2 weeks"),
                    ("monthly", "Monthly"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
