# Generated by Django 4.2.7 on 2026-01-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0005_meeting_attendees_emails_meeting_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalroom",
            name="is_locked",
            field=models.BooleanField(
                default=False,
                help_text="When locked, participants need approval to join",
            ),
        ),
    ]
