# Generated by Django 4.2.7 on 2026-01-28 10:34

from django.db import migrations


def lock_all_rooms(apps, schema_editor):
    """Set all existing personal rooms to locked"""
    PersonalRoom = apps.get_model('meetings', 'PersonalRoom')
    PersonalRoom.objects.all().update(is_locked=True)


def unlock_all_rooms(apps, schema_editor):
    """Reverse: unlock all rooms"""
    PersonalRoom = apps.get_model('meetings', 'PersonalRoom')
    PersonalRoom.objects.all().update(is_locked=False)


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0006_add_is_locked_to_personalroom"),
    ]

    operations = [
        migrations.RunPython(lock_all_rooms, unlock_all_rooms),
    ]
