# Generated by Django 4.2.7 on 2026-01-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0007_set_existing_rooms_locked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalroom",
            name="is_locked",
            field=models.BooleanField(
                default=True,
                help_text="When locked, participants need approval to join",
            ),
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(
                fields=["organization", "start_time"],
                name="meetings_me_organiz_49b85a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(
                fields=["organization", "is_private"],
                name="meetings_me_organiz_2e81c4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(
                fields=["start_time"], name="meetings_me_start_t_7a37c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(
                fields=["created_at"], name="meetings_me_created_3aac2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personalroom",
            index=models.Index(
                fields=["organization", "is_active"],
                name="meetings_pe_organiz_4a3c37_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usermeetingpacket",
            index=models.Index(
                fields=["room_id"], name="meetings_us_room_id_a7f529_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usermeetingpacket",
            index=models.Index(
                fields=["room_id", "user"], name="meetings_us_room_id_aa5fc9_idx"
            ),
        ),
    ]
