# Generated by Django 5.2.10 on 2026-02-04 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0008_alter_personalroom_is_locked_and_more"),
        ("users", "0005_organization_recording_to_s3"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meetingrecording",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="meetingrecording",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recordings",
                to="users.organization",
            ),
        ),
        migrations.AddField(
            model_name="meetingrecording",
            name="recording_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="meetingrecording",
            name="s3_key",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="meetingrecording",
            name="meeting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recordings",
                to="meetings.meeting",
            ),
        ),
        migrations.AddIndex(
            model_name="meetingrecording",
            index=models.Index(
                fields=["recorded_by", "-created_at"],
                name="meetings_me_recorde_23b36a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="meetingrecording",
            index=models.Index(
                fields=["organization", "-created_at"],
                name="meetings_me_organiz_15ec4c_idx",
            ),
        ),
    ]
