# Generated by Django 5.2.10 on 2026-02-06 12:00

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0009_alter_meetingrecording_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BreakoutRoom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("room_id", models.CharField(max_length=30, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "parent_meeting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breakout_rooms",
                        to="meetings.meeting",
                    ),
                ),
                (
                    "parent_room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breakout_rooms",
                        to="meetings.personalroom",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="breakoutroom",
            index=models.Index(
                fields=["parent_room", "is_active"], name="meetings_br_parent__8f3a9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="breakoutroom",
            index=models.Index(
                fields=["parent_meeting", "is_active"], name="meetings_br_parent__2c7e4d_idx"
            ),
        ),
    ]
