# Generated by Django 6.0.2 on 2026-02-07 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0010_breakoutroom'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='breakoutroom',
            new_name='meetings_br_parent__caabfb_idx',
            old_name='meetings_br_parent__8f3a9c_idx',
        ),
        migrations.RenameIndex(
            model_name='breakoutroom',
            new_name='meetings_br_parent__e65c1d_idx',
            old_name='meetings_br_parent__2c7e4d_idx',
        ),
    ]
