# Generated by Django 5.2.10 on 2026-02-14 20:19

import secrets
from django.db import migrations, models


def populate_attendee_tokens(apps, schema_editor):
    """Generate attendee_token for existing meetings that don't have one."""
    Meeting = apps.get_model('meetings', 'Meeting')
    for meeting in Meeting.objects.filter(attendee_token__isnull=True):
        meeting.attendee_token = secrets.token_urlsafe(32)
        meeting.save(update_fields=['attendee_token'])


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0010_breakoutroom"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="attendee_token",
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True, unique=True
            ),
        ),
        migrations.RunPython(populate_attendee_tokens, migrations.RunPython.noop),
    ]
