# Generated by Django 6.0.2 on 2026-02-14 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0011_add_meeting_attendee_token'),
        ('meetings', '0011_rename_meetings_br_parent__8f3a9c_idx_meetings_br_parent__caabfb_idx_and_more'),
    ]

    operations = [
    ]
