# Generated by Django 6.0.4 on 2026-04-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0016_add_livekit_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="connectionlog",
            new_name="meetings_co_room_id_6aaf58_idx",
            old_name="meetings_co_room_id_idx",
        ),
        migrations.RenameIndex(
            model_name="connectionlog",
            new_name="meetings_co_organiz_084b60_idx",
            old_name="meetings_co_org_idx",
        ),
        migrations.RenameIndex(
            model_name="meetingtranscript",
            new_name="meetings_me_room_id_a56f14_idx",
            old_name="meetings_me_room_id_transcript_idx",
        ),
        # NOTE: The auto-generated RemoveField operations for livekit_egress_id and
        # recording_status (added in 0016) and the AlterField that reverted file_path
        # to non-blank were removed because livekit_views.py writes to these fields
        # at runtime. Removing them caused start_recording / stop_recording / webhook
        # endpoints to crash. The model now exposes livekit_egress_id, status,
        # file_url and a nullable file_path (see migration 0019).
    ]
