# Generated by Django 6.0.4 on 2026-04-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0016_add_livekit_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="connectionlog",
            new_name="meetings_co_room_id_6aaf58_idx",
            old_name="meetings_co_room_id_idx",
        ),
        migrations.RenameIndex(
            model_name="connectionlog",
            new_name="meetings_co_organiz_084b60_idx",
            old_name="meetings_co_org_idx",
        ),
        migrations.RenameIndex(
            model_name="meetingtranscript",
            new_name="meetings_me_room_id_a56f14_idx",
            old_name="meetings_me_room_id_transcript_idx",
        ),
        migrations.RemoveField(
            model_name="meetingrecording",
            name="livekit_egress_id",
        ),
        migrations.RemoveField(
            model_name="meetingrecording",
            name="recording_status",
        ),
        migrations.AlterField(
            model_name="meetingrecording",
            name="file_path",
            field=models.CharField(max_length=500),
        ),
    ]
