# Generated by Django 5.2.10 on 2026-05-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "meetings",
            "0017_rename_meetings_co_room_id_idx_meetings_co_room_id_6aaf58_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalroom",
            name="is_locked",
            field=models.BooleanField(
                default=False,
                help_text="When locked, no one can join. When unlocked, guests need host approval.",
            ),
        ),
    ]
