# Generated by Django 5.2.10 on 2026-05-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0018_alter_personalroom_is_locked"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meetingrecording",
            name="recording_status",
        ),
        migrations.AddField(
            model_name="meetingrecording",
            name="file_url",
            field=models.URLField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="meetingrecording",
            name="status",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="meetingrecording",
            name="file_path",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="meetingrecording",
            name="livekit_egress_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
