# Generated by Django 4.2.7 on 2026-01-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_organization_profile_avatar_profile_updated_at_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["is_active"], name="users_organ_is_acti_43e248_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["created_at"], name="users_organ_created_d9273a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationmembership",
            index=models.Index(
                fields=["organization", "is_active"],
                name="users_organ_organiz_8323a1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="organizationmembership",
            index=models.Index(
                fields=["user", "organization", "is_active"],
                name="users_organ_user_id_d81853_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="organizationmembership",
            index=models.Index(
                fields=["organization", "role"], name="users_organ_organiz_532e4c_idx"
            ),
        ),
    ]
