# Generated by Django 4.2.7 on 2026-01-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_organization_users_organ_is_acti_43e248_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["current_organization"], name="users_profi_current_5fc19f_idx"
            ),
        ),
    ]
