# Generated by Django 5.2.10 on 2026-02-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_add_profile_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="recording_to_s3",
            field=models.BooleanField(
                default=False,
                help_text="Save recordings to cloud storage instead of local download",
            ),
        ),
    ]
