# Generated by Django 5.2.10 on 2026-02-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_organization_recording_to_s3"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="primary_color",
            field=models.CharField(blank=True, default="", max_length=7),
        ),
        migrations.AddField(
            model_name="organization",
            name="secondary_color",
            field=models.CharField(blank=True, default="", max_length=7),
        ),
        migrations.AddField(
            model_name="organization",
            name="subdomain",
            field=models.CharField(blank=True, max_length=63, null=True, unique=True),
        ),
    ]
