# Generated by Django 5.2.10 on 2026-02-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_add_branding_and_subdomain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="subdomain",
            field=models.CharField(
                blank=True, db_index=True, max_length=63, null=True, unique=True
            ),
        ),
    ]
